import { useEffect, useState } from "react"
import SoftBackdrop from "../components/SoftBackdrop"
import { type IThumbnail } from "../assets/assets"
import { Link, useNavigate } from "react-router-dom"
import { ArrowUpRightIcon, DownloadIcon } from "lucide-react"
import api from "../configs/api"
import toast from "react-hot-toast"

const Community = () => {
  const navigate = useNavigate();

  const aspectRatioClassMap: Record<string, string> = {
    "16:9": "aspect-video",
    "1:1": "aspect-square",
    "9:16": "aspect-[9/16]"
  }

  const [thumbnails, setThumbnails] = useState<IThumbnail[]>([])
  const [loading, setLoading] = useState(false)

  const fetchCommunityThumbnails = async () => {
    try {
      setLoading(true)
      const { data } = await api.get('/api/thumbnail/community')
      setThumbnails(data.thumbnails || [])
    } catch (error: any) {
      console.error(error);
      toast.error(error?.response?.data?.message || error.message)
    } finally {
      setLoading(false)
    }
  }

  const handleDownload = (image_url: string) => {
    const link = document.createElement('a');
    link.href = image_url.replace('/upload', '/upload/fl_attachment')
    document.body.appendChild(link)
    link.click()
    link.remove()
  }

  useEffect(() => {
    fetchCommunityThumbnails()
  }, [])

  return (
    <>
      <SoftBackdrop />
      <div className="mt-32 min-h-screen px-6 md:px-16 lg:px-24 xl:px-32">
        {/* HEADER */}
        <div className="mb-8">
          <h1 className="text-2xl font-bold text-zinc-200">Community Gallery</h1>
          <p className="text-sm text-zinc-400 mt-1">
            Discover amazing thumbnails generated by the community
          </p>
        </div>

        {/* LOADING */}
        {loading && (
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {Array.from({ length: 6 }).map((_, i) => (
              <div key={i} className="rounded-2xl bg-white/6 border border-white/10 animate-pulse h-[260px]" />
            ))}
          </div>
        )}

        {/* Empty State */}
        {!loading && thumbnails.length === 0 && (
          <div className="text-center py-24">
            <h3 className="text-lg font-semibold text-zinc-200">No public thumbnails yet</h3>
            <p className="text-sm text-zinc-400 mt-2">Generate a thumbnail and make it public to share it here!</p>
          </div>
        )}

        {/* Grid Layout */}
        {!loading && thumbnails.length > 0 && (
          <div className="columns-1 sm:columns-2 lg:columns-3 2xl:columns-4 gap-8">
            {thumbnails.map((thumb: IThumbnail) => {
              const aspectClass = aspectRatioClassMap[thumb.aspect_ratio || '16:9'];
              return (
                <div key={thumb._id} className="mb-8 group relative rounded-2xl bg-white/6 border border-white/10 transition shadow-xl break-inside-avoid overflow-hidden">
                  
                  {/* IMAGE */}
                  <div className={`relative overflow-hidden ${aspectClass} bg-black`}>
                    {thumb.image_url ? (
                      <img src={thumb.image_url} alt={thumb.title} className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-300" />
                    ) : (
                      <div className="w-full h-full flex items-center justify-center text-sm text-zinc-400">
                        {thumb.isGenerating ? 'Generating...' : 'No Image'}
                      </div>
                    )}
                  </div>

                  {/* Content */}
                  <div className="p-4 space-y-2">
                    <h3 className="text-sm font-semibold text-zinc-100 line-clamp-2">{thumb.title}</h3>

                    <div className="flex flex-wrap gap-2 text-xs text-zinc-400">
                      <span className="px-2 py-0.5 rounded bg-white/8">{thumb.style}</span>
                      <span className="px-2 py-0.5 rounded bg-white/8">{thumb.color_scheme}</span>
                      {/* Note: thumb.userId might be populated with user details if added in backend */}
                    </div>
                  </div>

                  {/* Hover Icons Overlay with Floating Tooltips */}
                  <div onClick={(e) => e.stopPropagation()} className="absolute bottom-2 right-2 max-sm:flex sm:hidden group-hover:flex items-center gap-1.5 z-10">
                    
                    {/* Download Button */}
                    <div className="relative group/tooltip">
                      <button
                        onClick={() => handleDownload(thumb.image_url!)}
                        className="size-7 bg-black/70 p-1.5 rounded-lg hover:bg-pink-600 transition-all cursor-pointer text-white flex items-center justify-center backdrop-blur-md border border-white/10"
                      >
                        <DownloadIcon className="size-full" />
                      </button>
                      <div className="absolute -top-9 left-1/2 -translate-x-1/2 opacity-0 group-hover/tooltip:opacity-100 transition-all duration-200 pointer-events-none z-30">
                        <div className="bg-zinc-900/95 text-white border border-white/15 text-[11px] font-medium px-2 py-0.5 rounded-md shadow-xl whitespace-nowrap">
                          Download
                        </div>
                        <div className="w-1.5 h-1.5 bg-zinc-900/95 rotate-45 mx-auto -mt-1 border-r border-b border-white/15"></div>
                      </div>
                    </div>

                    {/* YT Preview Button */}
                    <div className="relative group/tooltip">
                      <Link 
                        target="_blank" 
                        to={`/preview?thumbnail_url=${encodeURIComponent(thumb.image_url || '')}&title=${encodeURIComponent(thumb.title)}`}
                        className="size-7 bg-black/70 p-1.5 rounded-lg hover:bg-pink-600 transition-all text-white flex items-center justify-center backdrop-blur-md border border-white/10 cursor-pointer"
                      >
                        <ArrowUpRightIcon className="size-full" />
                      </Link>
                      <div className="absolute -top-9 left-1/2 -translate-x-1/2 opacity-0 group-hover/tooltip:opacity-100 transition-all duration-200 pointer-events-none z-30">
                        <div className="bg-zinc-900/95 text-white border border-white/15 text-[11px] font-medium px-2 py-0.5 rounded-md shadow-xl whitespace-nowrap">
                          YT Preview
                        </div>
                        <div className="w-1.5 h-1.5 bg-zinc-900/95 rotate-45 mx-auto -mt-1 border-r border-b border-white/15"></div>
                      </div>
                    </div>

                  </div>

                </div>
              )
            })}
          </div>
        )}
      </div>
    </>
  )
}

export default Community
